### ISSUE TITLE
ng lint with take(1) should be legit

### ISSUE THREAD

**Issue by ofirrifo** [angular-extensions/lint-rules#2]
I'm using a large project where we are use different type of operator in order to unsubscribe from observable.

for example take(1) operator or the Subscription
in this case this lint rules show me error.

I think this package is good but I can't use it as there more then one option for unsubscribe.
I be-live I'm not the only one how want to use it but can't as mention above.

Thanks

**Comment by macjohnny** [comment]
hey, thanks for your feedback.
consider the following case:
```typescript
someComponentMethod() {
  this.someService.observableThatNeverEmits$.pipe(take(1)).subscribe(() => {
    this.doSomething();
  })
}
```
this causes a memory leak even though the `take(1)` operator was used if the source observable never emits. 
whether or not an observable emits cannot be determined by static code analysis.

concerning the other ways to unsubscribe: there are definitely several ways to unsubscribe, e.g.
```typescript
subscriptions = [];
...
subscriptions.push(this.someService.someObservable$.subscribe())
...
ngOnDestroy() {
  this.subscriptions.forEach(subscription => subscription.unsubscribe())
}
```
However, all these possibilities require an implementation of a separate lint rule. if you want to implement this, you are very welcome to share your contribution.
